pipeline {
    agent any

    environment {
        DEMO='1.3'
    }

    stages {
        stage('stage-1') {
            steps {
                echo "This is build number $BUILD_NUMBER of $DEMO"
                sh '''
                    echo "Using a multi-line shell"
                    chmod +x ./1.0/test.sh
                    ./1.0/test.sh
                '''
            }
        }
    }
}