pipeline {
    agent any

    environment {
        RELEASE='0.0.1'
    }

    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }

        stage('Test') {
            steps {
                // echo "I can see  release ${RELEASE} but not log level ${LOG_LEVEL}..."
                echo "I can see  release ${RELEASE} but not log level..."
            }
        }

        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }

            steps {
                echo "Deploying ${RELEASE} to ${TARGET_ENVIRONMENT}"
            }
        }
    }

    post {
        always {
            echo "Prints wether deploy happened or not, success or failure"
        }
    }
}